---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/line_bot
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
line.bot:
  channel-token: ${CHANNEL_TOKEN}
  channel-secret: ${CHANNEL_SECRET}
  handler.path: /callback
bus:
  app-id: ${BUS_APP_ID}
  app-key: ${BUS_APP_KEY}